### ISSUE TITLE
Change in MatTable dataSource is not reflecting in UI

### ISSUE THREAD

**Issue by udaychy** [ajtowf/angularmaterial#1]
Hi @ajtowf 
I was going through your [AngularMaterial Course](https://app.pluralsight.com/library/courses/angular-material) and I stuck at a point where you have used `setTimeout` method in [_main-content.component.ts_](https://github.com/ajtowf/angularmaterial/blob/master/src/app/contactmanager/components/main-content/main-content.component.ts)  to show the loader for enough time which looks cool BUT if I DONOT use `setTimeout` method then I am getting some issues with Notes binding. 
Any change in MatTable's dataSource is not reflecting in UI. 
I tried plain `Note` Array and  `BehaviorSubject` of type `Note` as the dataSource but I didn't get the expected output. 

I know this is the issue related to Angular Material Table but still It will be very helpful if you figure out this issue.

Thanks
Uday

**Comment by ajtowf** [comment]
Ported course to angular 10, check it out: https://github.com/ajtowf/styling-angular-applications
