### ISSUE TITLE
project not compatible with angular CLI

### ISSUE THREAD

**Issue by chetouimohamedaziz** [ajtowf/angularmaterial#3]
when make ng serve i have this error

> To disable this warning use "ng config -g cli.warnings.versionMismatch false".
> internal/modules/cjs/loader.js:583
>     throw err;
>     ^
> 
> Error: Cannot find module '@angular-devkit/core'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (C:\Users\medaziz\Desktop\simulator\angularmaterial\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by chetouimohamedaziz** [comment]
error related to this issue

[Error: Cannot find module '@angular-devkit/core' - after clean install #9307](https://github.com/angular/angular-cli/issues/9307) 

and the solution is in a comment of
> LarsMengel commented on Jan 21, 2018

```
npm update -g @angular/cli
editing my package.json changing the line
"@angular/cli": "1.6.0",
to
"@angular/cli": "^1.6.0",
npm update
did the trick.
```

**Comment by chetouimohamedaziz** [comment]
this error is related to module8 and i think not in master branch

> package.json
```
"devDependencies": {
    ...
    "@angular/cli": "^1.7.3",
    ...
  }
```

**Comment by ajtowf** [comment]
Ported course to angular 10, check it out: https://github.com/ajtowf/styling-angular-applications
